name-template: v$NEXT_PATCH_VERSION 🌈
tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: Features
    label: enhancement
  - title: Bug Fixes
    label: bug
  - title: Maintenance
    label: maintainability
  - title: Documentation
    label: documentation
  - title: Dependencies and Libraries
    label: dependencies
  - title: Enhancements
    label: enhancement
  - title: Web UI Improvements
    label: UI
change-template: '- $TITLE (#$NUMBER) - @$AUTHOR'
template: |
  ## Changes

  $CHANGES
  
  
  ## Contributors
  
  Thanks a lot to our contributors for making this release possible:
  $CONTRIBUTORS
