// Generated by the windmill services transformer
var test_recordingSuite0 = new function() {
    this.test_actions = [
{"params": {"link": "Food"}, "method": "click"},
{"params": {"timeout": "20000"}, "method": "waits.forPageLoad"},
{"params": {"xpath": "//div[@id='body']/div[1]/div[2]/table/tbody/tr[1]/td[3]/table/tbody/tr/td[2]/a", "timeout": "8000"}, "method": "waits.forElement"},
{"params": {"xpath": "//div[@id='body']/div[1]/div[2]/table/tbody/tr[1]/td[3]/table/tbody/tr/td[2]/a"}, "method": "click"},
{"params": {"xpath": "Error - Could not find a reliable locator for this node."}, "method": "click"},
{"params": {"xpath": "/html/body/div[5]/div/div[2]/div/table/tbody/tr[2]/td[1]/div/textarea"}, "method": "click"},
{"params": {"xpath": "/html/body/div[5]/div/div[2]/div/table/tbody/tr[2]/td[1]/div/textarea", "text": "value.split(\",\")[0]"}, "method": "type"},
{"params": {"xpath": "Error - Could not find a reliable locator for this node."}, "method": "click"},
{"params": {"link": "BEEF"}, "method": "click"},
{"params": {"xpath": "//div[@id='body']/div[1]/div[2]/table/tbody/tr[1]/td[4]/table/tbody/tr/td[2]/a"}, "method": "click"},
{"params": {"xpath": "Error - Could not find a reliable locator for this node."}, "method": "click"},
{"params": {"xpath": "//div[@id='body']/div[1]/div[1]/span/span"}, "method": "click"}
    ];
}
