blank_issues_enabled: false
contact_links:
  - name: Ask a question (forum)
    url: https://forum.openrefine.org/
    about: Please ask and answer questions here.
  - name: Gitter chat
    url: https://gitter.im/OpenRefine/OpenRefine
    about: General and developer discussions
