#!/bin/bash

printf '[Desktop Entry]\nName=OpenRefine\nVersion=2.8\nExec=/opt/openrefine/refine\nComment=Application for data cleanup\nIcon=/opt/openrefine/icon.png\nType=Application\nTerminal=true\nStartupNotify=false\nEncoding=UTF-8\nCategories=Utility;\n' | sudo tee '/usr/share/applications/openrefine.desktop'

printf '\nexport PATH=$PATH:/opt/openrefine\n' | tee -a ~/.profile
source ~/.profile

