/*******************************************************************************
 * Copyright (C) 2026, OpenRefine contributors
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/

package com.google.refine.model.changes;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertTrue;

import java.io.IOException;
import java.io.StringWriter;
import java.io.Writer;
import java.util.Properties;

import org.slf4j.LoggerFactory;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import com.google.refine.RefineTest;
import com.google.refine.history.Change;
import com.google.refine.history.SaveOptions;
import com.google.refine.model.Project;
import com.google.refine.util.Pool;

/**
 * Initial implementation generated by Claude 4.5 Haiku
 */
public class LegacyChangeTests extends RefineTest {

    @Override
    @BeforeTest
    public void init() {
        logger = LoggerFactory.getLogger(this.getClass());
    }

    /**
     * A legacy Change implementation that only overrides save(Writer, Properties), simulating old-style changes from
     * before SaveOptions was introduced.
     */
    public static class LegacyTestChange implements Change {

        private String testValue;

        public LegacyTestChange(String testValue) {
            this.testValue = testValue;
        }

        @Override
        public void apply(Project project) {
            // No-op for testing purposes
        }

        @Override
        public void revert(Project project) {
            // No-op for testing purposes
        }

        /**
         * Old-style save method - only this is implemented, not the new SaveOptions version.
         */
        @Override
        public void save(Writer writer, Properties options) throws IOException {
            writer.write("testValue=");
            writer.write(testValue);
            writer.write('\n');

            if (options != null && options.containsKey("mode")) {
                writer.write("mode=");
                writer.write((String) options.get("mode"));
                writer.write('\n');
            }

            writer.write("/ec/\n");
        }
    }

    /**
     * Test that old-style Change implementations can be saved using SaveOptions.DEFAULT. This verifies backward
     * compatibility - calling save(Writer, SaveOptions) on a legacy Change should properly delegate to save(Writer,
     * Properties).
     */
    @Test
    public void testLegacyChangeSaveWithDefaultOptions() throws IOException {
        LegacyTestChange change = new LegacyTestChange("oldStyleValue");
        StringWriter writer = new StringWriter();

        // This should work - the new API should delegate to the old one
        change.save(writer, SaveOptions.DEFAULT);

        String result = writer.toString();
        assertTrue(result.contains("testValue=oldStyleValue"),
                "Output should contain the test value");
        assertTrue(result.contains("/ec/"),
                "Output should contain end of change marker");
    }

    /**
     * Test that old-style Change implementations properly receive converted SaveOptions when called through the new
     * API.
     */
    @Test
    public void testLegacyChangeSaveWithSaveModeOptions() throws IOException {
        LegacyTestChange change = new LegacyTestChange("legacyData");
        StringWriter writer = new StringWriter();

        // Create SaveOptions with save mode enabled
        SaveOptions options = new SaveOptions(true);
        change.save(writer, options);

        String result = writer.toString();
        assertTrue(result.contains("testValue=legacyData"),
                "Output should contain the test value");
        assertTrue(result.contains("mode=save"),
                "Output should contain mode=save when save mode is enabled");
        assertTrue(result.contains("/ec/"),
                "Output should contain end of change marker");
    }

    /**
     * Test that old-style Change implementations work with Pool in SaveOptions.
     */
    @Test
    public void testLegacyChangeSaveWithPoolOptions() throws IOException {
        LegacyTestChange change = new LegacyTestChange("pooledData");
        StringWriter writer = new StringWriter();

        // Create SaveOptions with a Pool
        Pool pool = new Pool();
        SaveOptions options = new SaveOptions(true, pool);
        change.save(writer, options);

        String result = writer.toString();
        assertTrue(result.contains("testValue=pooledData"),
                "Output should contain the test value");
        assertTrue(result.contains("mode=save"),
                "Output should contain mode=save");
        assertTrue(result.contains("/ec/"),
                "Output should contain end of change marker");
    }

    /**
     * Test that multiple legacy changes can all be saved properly. This ensures the delegation mechanism works
     * consistently across multiple instances.
     */
    @Test
    public void testMultipleLegacyChangesSaveConsistently() throws IOException {
        String[] testValues = { "value1", "value2", "value3" };

        for (String value : testValues) {
            LegacyTestChange change = new LegacyTestChange(value);
            StringWriter writer = new StringWriter();

            change.save(writer, SaveOptions.DEFAULT);

            String result = writer.toString();
            assertTrue(result.contains("testValue=" + value),
                    "Output should contain testValue=" + value);
            assertTrue(result.contains("/ec/"),
                    "Output should contain end of change marker");
        }
    }

    /**
     * Test that the exact format of legacy change output matches expectations. This verifies that the delegation
     * properly preserves the format.
     */
    @Test
    public void testLegacyChangeSaveFormat() throws IOException {
        LegacyTestChange change = new LegacyTestChange("exactTest");
        StringWriter writer = new StringWriter();

        change.save(writer, SaveOptions.DEFAULT);

        String result = writer.toString();
        String[] lines = result.split("\n");

        assertEquals(lines[0], "testValue=exactTest",
                "First line should be the test value");
        assertEquals(lines[1], "/ec/",
                "Second line should be the end of change marker");
    }

    /**
     * Test that legacy changes save format with save mode option.
     */
    @Test
    public void testLegacyChangeSaveFormatWithMode() throws IOException {
        LegacyTestChange change = new LegacyTestChange("modeTest");
        StringWriter writer = new StringWriter();

        change.save(writer, new SaveOptions(true));

        String result = writer.toString();
        String[] lines = result.split("\n");

        assertEquals(lines[0], "testValue=modeTest",
                "First line should be the test value");
        assertEquals(lines[1], "mode=save",
                "Second line should be the save mode");
        assertEquals(lines[2], "/ec/",
                "Third line should be the end of change marker");
    }
}
