describe(__filename, function () {
    it('Ensure it shows correct number of rows', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('#summary-bar').should('to.contain', '199 rows')
    })
    it('Ensure it shows only 5 rows when pagesize is 5', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('5').click()
        cy.get('.data-table tbody').find('tr').should('have.length', 5)
        cy.get('.data-table tbody>tr')
            .eq(0)
            .should('to.contain', 'BUTTER,WITH SALT')
        cy.get('.data-table tbody>tr')
            .eq(4)
            .should('to.contain', 'CHEESE,BRICK')
    })
    it('Ensure it shows only 10 rows when pagesize is 10', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('10').click()
        cy.get('.data-table tbody').find('tr').should('have.length', 10)
        cy.get('.data-table tbody>tr')
            .eq(0)
            .should('to.contain', 'BUTTER,WITH SALT')
        cy.get('.data-table tbody>tr')
            .eq(9)
            .should('to.contain', 'CHEESE,CHESHIRE')
    })
    it('Ensure it shows only 25 rows when pagesize is 25', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('25').click()
        cy.get('.data-table tbody').find('tr').should('have.length', 25)
        cy.get('.data-table tbody>tr')
            .eq(0)
            .should('to.contain', 'BUTTER,WITH SALT')
        cy.get('.data-table tbody>tr')
            .eq(24)
            .should('to.contain', 'CHEESE,MONTEREY')
    })
    it('Ensure it shows only 50 rows when pagesize is 50', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('50').click()
        cy.get('.data-table tbody').find('tr').should('have.length', 50)
        cy.get('.data-table tbody>tr')
            .eq(0)
            .should('to.contain', 'BUTTER,WITH SALT')
        cy.get('.data-table tbody>tr')
            .eq(49)
            .should('to.contain', 'CREAM,FLUID,LT (COFFEE CRM OR TABLE CRM)')
    })
    it('Ensure it redirects to next-page when pagesize is 5', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('5').click()
        cy.get('.viewpanel-paging').find('a').contains('next').click()
        cy.get('#viewpanel-paging-current-input').should('have.value', 2)
        cy.get('.data-table tbody>tr').eq(0).should('to.contain', 'CHEESE,BRIE')
        cy.get('.data-table tbody>tr')
            .eq(4)
            .should('to.contain', 'CHEESE,CHESHIRE')
    })
    it('Ensure it redirects to next-page when pagesize is 10', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('10').click()
        cy.get('.viewpanel-paging').find('a').contains('next').click()
        cy.get('#viewpanel-paging-current-input').should('have.value', 2)
        cy.get('.data-table tbody>tr')
            .eq(0)
            .should('to.contain', 'CHEESE,COLBY')
        cy.get('.data-table tbody>tr')
            .eq(9)
            .should('to.contain', 'CHEESE,FONTINA')
    })
    it('Ensure it redirects to next-page when pagesize is 25', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('25').click()
        cy.get('.viewpanel-paging').find('a').contains('next').click()
        cy.get('#viewpanel-paging-current-input').should('have.value', 2)
        cy.get('.data-table tbody>tr')
            .eq(0)
            .should('to.contain', 'CHEESE,MOZZARELLA,WHL MILK')
        cy.get('.data-table tbody>tr')
            .eq(24)
            .should('to.contain', 'CREAM,FLUID,LT (COFFEE CRM OR TABLE CRM)')
    })
    it('Ensure it redirects to next-page when pagesize is 50', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('50').click()
        cy.get('.viewpanel-paging').find('a').contains('next').click()
        cy.get('#viewpanel-paging-current-input').should('have.value', 2)
        cy.get('.data-table tbody>tr')
            .eq(0)
            .should('to.contain', 'CREAM,FLUID,LT WHIPPING')
        cy.get('.data-table tbody>tr')
            .eq(49)
            .should('to.contain', 'MILK SHAKES,THICK VANILLA')
    })
    it('Ensure last button redirects to last-page when pagesize is 5', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('5').click()
        cy.get('.viewpanel-paging').find('a').contains('last').click()
        cy.get('#viewpanel-paging-current-input').should('have.value', 40)
        cy.get('.data-table tbody>tr')
            .eq(0)
            .should('to.contain', 'CHERVIL,DRIED')
        cy.get('.data-table tbody>tr')
            .eq(3)
            .should('to.contain', 'CLOVES,GROUND')
    })
    it('Ensure last button redirects to last-page when pagesize is 10', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('10').click()
        cy.get('.viewpanel-paging').find('a').contains('last').click()
        cy.get('#viewpanel-paging-current-input').should('have.value', 20)
        cy.get('.data-table tbody>tr')
            .eq(0)
            .should('to.contain', 'SPICES,BASIL,DRIED')
        cy.get('.data-table tbody>tr')
            .eq(8)
            .should('to.contain', 'CLOVES,GROUND')
    })
    it('Ensure last button redirects to last-page when pagesize is 25', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('25').click()
        cy.get('.viewpanel-paging').find('a').contains('last').click()
        cy.get('#viewpanel-paging-current-input').should('have.value', 8)
        cy.get('.data-table tbody>tr')
            .eq(0)
            .should(
                'to.contain',
                "KRAFT BREYERS LT N' LVLY LOWFAT STR'BERY YOGURT (1% MILKFAT)"
            )
        cy.get('.data-table tbody>tr')
            .eq(23)
            .should('to.contain', 'CLOVES,GROUND')
    })
    it('Ensure last button redirects to last-page when pagesize is 50', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('50').click()
        cy.get('.viewpanel-paging').find('a').contains('last').click()
        cy.get('#viewpanel-paging-current-input').should('have.value', 4)
        cy.get('.data-table tbody>tr')
            .eq(0)
            .should('to.contain', 'CHEESE SAU,PREP FROM RECIPE')
        cy.get('.data-table tbody>tr')
            .eq(48)
            .should('to.contain', 'CLOVES,GROUND')
    })
    it('Ensure first button redirects to first-page when pagesize is 5', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('5').click()
        cy.get('.viewpanel-paging').find('a').contains('last').click()
        cy.get('#viewpanel-paging-current-input').should('have.value', 40)
        cy.get('.viewpanel-paging').find('a').contains('first').click()
        cy.get('#viewpanel-paging-current-input').should('have.value', 1)
        cy.get('.data-table tbody>tr')
            .eq(0)
            .should('to.contain', 'BUTTER,WITH SALT')
        cy.get('.data-table tbody>tr')
            .eq(4)
            .should('to.contain', 'CHEESE,BRICK')
    })
    it('Ensure first button redirects to first-page when pagesize is 10', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('10').click()
        cy.get('.viewpanel-paging').find('a').contains('last').click()
        cy.get('#viewpanel-paging-current-input').should('have.value', 20)
        cy.get('.viewpanel-paging').find('a').contains('first').click()
        cy.get('#viewpanel-paging-current-input').should('have.value', 1)
        cy.get('.data-table tbody>tr')
            .eq(0)
            .should('to.contain', 'BUTTER,WITH SALT')
        cy.get('.data-table tbody>tr')
            .eq(9)
            .should('to.contain', 'CHEESE,CHESHIRE')
    })
    it('Ensure first button redirects to first-page when pagesize is 25', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('25').click()
        cy.get('.viewpanel-paging').find('a').contains('last').click()
        cy.get('#viewpanel-paging-current-input').should('have.value', 8)
        cy.get('.viewpanel-paging').find('a').contains('first').click()
        cy.get('#viewpanel-paging-current-input').should('have.value', 1)
        cy.get('.data-table tbody>tr')
            .eq(0)
            .should('to.contain', 'BUTTER,WITH SALT')
        cy.get('.data-table tbody>tr')
            .eq(24)
            .should('to.contain', 'CHEESE,MONTEREY')
    })
    it('Ensure first button redirects to first-page when pagesize is 50', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('50').click()
        cy.get('.viewpanel-paging').find('a').contains('last').click()
        cy.get('#viewpanel-paging-current-input').should('have.value', 4)
        cy.get('.viewpanel-paging').find('a').contains('first').click()
        cy.get('#viewpanel-paging-current-input').should('have.value', 1)
        cy.get('.data-table tbody>tr')
            .eq(0)
            .should('to.contain', 'BUTTER,WITH SALT')
        cy.get('.data-table tbody>tr')
            .eq(49)
            .should('to.contain', 'CREAM,FLUID,LT (COFFEE CRM OR TABLE CRM)')
    })
    it('Ensure page-number input redirects to correct-page when pagesize is 5', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('5').click()
        cy.get('#viewpanel-paging-current-input').type('{backspace}2{enter}')
        cy.get('#viewpanel-paging-current-input').should('have.value', 2)
        cy.get('.data-table tbody>tr').eq(0).should('to.contain', 'CHEESE,BRIE')
        cy.get('.data-table tbody>tr')
            .eq(4)
            .should('to.contain', 'CHEESE,CHESHIRE')
    })
    it('Ensure page-number input redirects to correct-page when pagesize is 10', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('10').click()
        cy.get('#viewpanel-paging-current-input').type('{backspace}2{enter}')
        cy.get('#viewpanel-paging-current-input').should('have.value', 2)
        cy.get('.data-table tbody>tr')
            .eq(0)
            .should('to.contain', 'CHEESE,COLBY')
        cy.get('.data-table tbody>tr')
            .eq(9)
            .should('to.contain', 'CHEESE,FONTINA')
    })
    it('Ensure page-number input redirects to correct-page when pagesize is 25', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('25').click()
        cy.get('#viewpanel-paging-current-input').type('{backspace}2{enter}')
        cy.get('#viewpanel-paging-current-input').should('have.value', 2)
        cy.get('.data-table tbody>tr')
            .eq(0)
            .should('to.contain', 'CHEESE,MOZZARELLA,WHL MILK')
        cy.get('.data-table tbody>tr')
            .eq(24)
            .should('to.contain', 'CREAM,FLUID,LT (COFFEE CRM OR TABLE CRM)')
    })
    it('Ensure page-number input redirects to correct-page when pagesize is 50', function () {
        cy.loadAndVisitProject('food.small')

        cy.get('.viewpanel-pagesize').find('a').contains('50').click()
        cy.get('#viewpanel-paging-current-input').type('{backspace}2{enter}')
        cy.get('#viewpanel-paging-current-input').should('have.value', 2)
        cy.get('.data-table tbody>tr')
            .eq(0)
            .should('to.contain', 'CREAM,FLUID,LT WHIPPING')
        cy.get('.data-table tbody>tr')
            .eq(49)
            .should('to.contain', 'MILK SHAKES,THICK VANILLA')
    })
})
