name: openrefine
base: core20
version: '3.5.2'
summary: A free, open source, powerful tool for working with messy data
description: |
  OpenRefine (previously Google Refine) is a powerful tool for working with messy data:
  cleaning it; transforming it from one format into another; and extending it with web services and external data.
  OpenRefine always keeps your data private on your own computer until YOU want to share or collaborate. Your private data never leaves your computer unless you want it to. (It works by running a small server on your computer and you use your web browser to interact with it)

grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
  
layout:
  /usr/bin/free:
    bind-file: $SNAP/usr/bin/free

parts:
  openrefine:
    plugin: dump
    source: https://github.com/OpenRefine/OpenRefine/releases/download/$SNAPCRAFT_PROJECT_VERSION/openrefine-linux-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    stage-packages:
      - default-jre
      - wget
      - ca-certificates-java 
    prime:
      - -usr/lib/jvm/java-*/lib/security/cacerts
      - -usr/lib/jvm/java-*/jre/lib/security/cacerts

apps:
  openrefine:
    command: ./refine
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
      _JAVA_OPTIONS: -Duser.home="${SNAP_USER_DATA}"
    plugs:
      - home
      - network
      - network-bind
      - x11
