name: Cypress CI

on: [push]

jobs:
    build:
        strategy:
            matrix:
                browser: ['chrome']

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2.3.4

            - name: Restore dependency cache
              uses: actions/cache@v2.1.3
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-

            - name: Set up Java 8
              uses: actions/setup-java@v1
              with:
                  java-version: 8

            - name: Prepare Maven Pom
              uses: canastro/copy-file-action@master
              with:
                source: "packaging/test_pom.xml"
                target: "packaging/pom.xml"
                
            - name: Build with Maven
              run: mvn process-resources

            - name: Restore Tests dependency cache
              uses: actions/cache@v2.1.3
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/main/tests/cypress/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn

            - name: Install test dependencies
              run: |
                  cd ./main/tests/cypress
                  yarn install

            - name: Test with Cypress on ${{ matrix.browser }}
              run: ./refine ui_test ${{ matrix.browser }}