name: Cypress CI

on: [pull_request_target]

jobs:
    build:
        strategy:
            matrix:
                browser: ['chrome']

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2.3.4

            - name: Restore dependency cache
              uses: actions/cache@v2.1.3
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-

            - name: Set up Java 8
              uses: actions/setup-java@v1
              with:
                  java-version: 8

            - name: Build OpenRefine
              run: ./refine build

            - name: Restore Tests dependency cache
              uses: actions/cache@v2.1.3
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn

            - name: Install test dependencies
              run: |
                  cd ./main/tests/cypress
                  yarn install

            - name: Test with Cypress on ${{ matrix.browser }}
              run: | 
                echo REFINE_MIN_MEMORY=1400M >> ./refine.ini
                echo REFINE_MEMORY=4096M >> ./refine.ini
                ./refine ui_test ${{ matrix.browser }} s5du3k "${{ secrets.CYPRESS_RECORD_KEY }}"